/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package tech.nermindedovic.papitutorial.models.avro;
@org.apache.avro.specific.AvroGenerated
public enum Power implements org.apache.avro.generic.GenericEnumSymbol<Power> {
  ON, OFF  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Power\",\"namespace\":\"tech.nermindedovic.papitutorial.models.avro\",\"symbols\":[\"ON\",\"OFF\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
